
project_id = "uysdqwhyhqhamwvzsolw"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[functions]
[functions.train-model]
verify_jwt = false
[functions.predict-with-model]
verify_jwt = false
[functions.generate-colab-notebook]
verify_jwt = false
[functions.import-trained-model]
verify_jwt = false

[storage]
