// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uysdqwhyhqhamwvzsolw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5c2Rxd2h5aHFoYW13dnpzb2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTM2MjQsImV4cCI6MjA1NTY4OTYyNH0.0Z2oSF4xvjbKzzqA-j_R5HlIkYGah-UagKnGiGI20dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);